"""Reproducibility contracts for APCC-1 empirical evaluation."""

from .contract import (
    ABLATION_IDS,
    ATTACK_IDS,
    AblationPerformanceCell,
    AttackTrial,
    ContractViolation,
    ExperimentMatrix,
    HashCounterPRNG,
    baseline_order,
    derive_attack_trial,
    load_matrix,
    load_raw_result,
    planned_ablation_performance_runs,
    planned_parser_trials,
    planned_ablation_trials,
    planned_formal_runs,
    planned_functional_trials,
    planned_performance_runs,
    planned_race_recovery_trials,
    planned_storage_runs,
    planned_timing_trials,
    planning_cardinalities,
    planned_attack_trials,
    store_order,
    validate_matrix,
)

__all__ = [
    "ABLATION_IDS",
    "ATTACK_IDS",
    "AblationPerformanceCell",
    "AttackTrial",
    "ContractViolation",
    "ExperimentMatrix",
    "HashCounterPRNG",
    "baseline_order",
    "derive_attack_trial",
    "load_matrix",
    "load_raw_result",
    "planned_ablation_performance_runs",
    "planned_parser_trials",
    "planned_ablation_trials",
    "planned_formal_runs",
    "planned_functional_trials",
    "planned_performance_runs",
    "planned_race_recovery_trials",
    "planned_storage_runs",
    "planned_timing_trials",
    "planning_cardinalities",
    "planned_attack_trials",
    "store_order",
    "validate_matrix",
]
